# Generated by Django 4.1.3 on 2024-10-21 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, unique=True)),
                ('explanation', models.TextField(null=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('Options', models.CharField(choices=[('Cost and Cost Reduction', 'Cost and Cost Reduction'), ('Productivity Increase', 'Productivity Increase'), ('Quality of Data Increase', 'Quality of Data Increase'), ('Safety Increase', 'Safety Increase'), ('Learning and Growth Increase', 'Learning and Growth Increase'), ('User Satisfaction', 'User Satisfaction')], max_length=100, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, unique=True)),
                ('explanation', models.TextField(null=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('UserType', models.CharField(choices=[('Service User', 'Service User'), ('Data Provider', 'Data Provider'), ('Service Stakeholder', 'Service Stakeholder')], max_length=100, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, unique=True)),
                ('explanation', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('BSCfamily', models.CharField(choices=[('Customer', 'Customer'), ('Financial', 'Financial'), ('Education and Growth', 'Education and Growth'), ('Internal Processes', 'Internal Porcesses')], max_length=100, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EVALUATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('ANPAHP_recommendations', models.TextField(blank=True, default='', null=True)),
                ('porcentage', models.TextField(default='', null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('action', models.TextField(default='', null=True)),
                ('UserType', models.CharField(choices=[('Service User', 'Service User'), ('Data Provider', 'Data Provider'), ('Service Stakeholder', 'Service Stakeholder')], max_length=100, null=True)),
                ('status1', models.BooleanField(default=False)),
                ('status2', models.BooleanField(default=False)),
                ('status3', models.BooleanField(default=False)),
                ('status4', models.BooleanField(default=False)),
                ('status5', models.BooleanField(default=False)),
                ('status6', models.BooleanField(default=False)),
                ('status7', models.BooleanField(default=False)),
                ('status8', models.BooleanField(default=False)),
                ('SelectedKPIs', models.TextField(default='[]', null=True)),
                ('Scores1', models.JSONField(default=dict, null=True)),
                ('Scores2', models.JSONField(default=dict, null=True)),
                ('Scores3', models.JSONField(default=dict, null=True)),
                ('Scores4', models.JSONField(default=dict, null=True)),
                ('inconcistency1', models.TextField(blank=True, default='[]', null=True)),
                ('inconcistency2', models.TextField(blank=True, default='[]', null=True)),
                ('inconcistency3', models.TextField(blank=True, default='[]', null=True)),
                ('inconcistency4', models.TextField(blank=True, default='[]', null=True)),
                ('vector1', models.JSONField(default=dict, null=True)),
                ('vector2', models.JSONField(default=dict, null=True)),
                ('vector3', models.JSONField(default=dict, null=True)),
                ('vector4', models.JSONField(default=dict, null=True)),
                ('pairwise_combinations', models.JSONField(default=dict, null=True)),
                ('KPIS_selected_names', models.TextField(blank=True, default='[]', null=True)),
                ('SelectedObjectives', models.TextField(default='[]', null=True)),
                ('Scores5', models.JSONField(default=dict, null=True)),
                ('inconcistency5', models.TextField(blank=True, default='[]', null=True)),
                ('vector5', models.JSONField(default=dict, null=True)),
                ('pairwise_combinations_objectives', models.JSONField(default=dict, null=True)),
                ('BSC_Weights', models.TextField(blank=True, default='[]', null=True)),
                ('SelectedCriterias', models.TextField(default='[]', null=True)),
                ('Scores6', models.JSONField(default=dict, null=True)),
                ('inconcistency6', models.TextField(blank=True, default='[]', null=True)),
                ('vector6', models.JSONField(default=dict, null=True)),
                ('pairwise_combinations_criterias', models.JSONField(default=dict, null=True)),
                ('Criterias_selected_names', models.TextField(blank=True, default='[]', null=True)),
                ('shapes', models.TextField(blank=True, default='[]', null=True)),
                ('matrix_data', models.JSONField(default=dict, null=True)),
                ('matrix_data_pre', models.TextField(default='[]', null=True)),
                ('results', models.TextField(default='[]', null=True)),
                ('hierarcy', models.TextField(default='[]', null=True)),
                ('supermatrix', models.TextField(default='[]', null=True)),
                ('rows', models.TextField(default='[]', null=True)),
                ('comments', models.TextField(default='[]', null=True)),
                ('message', models.TextField(default='[]', null=True)),
                ('User_domain', models.CharField(choices=[('Manufacturing', 'Manufacturing'), ('Aerospace', 'Aerospace'), ('Communications', 'Communications'), ('Chemical and Pharmaceutical', 'Chemical and pharmaceutical'), ('Consumer, Goods and Retail', 'Consumer, Goods and Retail'), ('Energy and Utilities', 'Energy and Utilities'), ('Financial services, Banking and Insurance', 'Financial services, Banking and Insurance'), ('Freight, Logistics and Transportation', 'Freight, Logistics and Transportation'), ('Health and Life Sciences', 'Health and Life Sciences'), ('Hospitality and travel', 'Hospitality and travel'), ('Media, entertainment, and publishing', 'Media, entertainment, and publishing'), ('R&D and Education', 'R&D and Education')], max_length=100, null=True)),
                ('Criterias', models.ManyToManyField(blank=True, to='ANPAHP.criteria')),
                ('KPIs', models.ManyToManyField(blank=True, to='ANPAHP.kpi')),
                ('Objectives', models.ManyToManyField(blank=True, to='ANPAHP.objective')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
