# Generated by Django 5.1.7 on 2025-04-01 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('explanation', models.TextField()),
                ('option', models.CharField(choices=[('COST_AND_COST_REDUCTION', 'Cost and Cost Reduction'), ('PRODUCTIVITY_INCREASE', 'Productivity Increase'), ('QUALITY_AND_DATA_INCREASE', 'Quality and Data Increase'), ('SAFETY_INCREASE', 'Safety Increase'), ('LEARNING_AND_GROWTH_INCREASE', 'Learning and Growth Increase'), ('USER_SATISFACTION', 'User Satisfaction')], max_length=100)),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('explanation', models.TextField()),
                ('BSCfamily', models.CharField(choices=[('CUSTOMER', 'Customer'), ('FINANCIAL', 'Financial'), ('EDUCATION AND GROWTH', 'Education and Growth'), ('INTERNAL PROCESSES', 'Internal Processes')], max_length=100)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('explanation', models.TextField()),
                ('user_type', models.CharField(choices=[('SERVICE_USER', 'Service User'), ('DATA_PROVIDER', 'Data Provider'), ('SERVICE_STAKEHOLDER', 'Service Stakeholder')], max_length=100)),
                ('last_updated', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('ANPAHP_recommendations', models.TextField(blank=True, default='')),
                ('percentage', models.TextField(default='0%')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('action', models.TextField(blank=True, default='')),
                ('user_type', models.CharField(choices=[('SERVICE_USER', 'Service User'), ('DATA_PROVIDER', 'Data Provider'), ('SERVICE_STAKEHOLDER', 'Service Stakeholder')], max_length=100)),
                ('step_status1', models.BooleanField(default=False)),
                ('step_status2', models.BooleanField(default=False)),
                ('step_status3', models.BooleanField(default=False)),
                ('step_status4', models.BooleanField(default=False)),
                ('step_status5', models.BooleanField(default=False)),
                ('step_status6', models.BooleanField(default=False)),
                ('step_status7', models.BooleanField(default=False)),
                ('step_status8', models.BooleanField(default=False)),
                ('selected_KPIs', models.TextField(default='[]')),
                ('financial_scores', models.JSONField(default=dict)),
                ('financial_inconcistency', models.TextField(default='[]')),
                ('financial_vector', models.JSONField(default=dict)),
                ('internal_processes_scores', models.JSONField(default=dict)),
                ('internal_processes_inconcistency', models.TextField(default='[]')),
                ('internal_processes_vector', models.JSONField(default=dict)),
                ('learn_growth_scores', models.JSONField(default=dict)),
                ('learn_growth_inconcistency', models.TextField(default='[]')),
                ('learn_growth_vector', models.JSONField(default=dict)),
                ('clients_scores', models.JSONField(default=dict)),
                ('clients_inconcistency', models.TextField(default='[]')),
                ('clients_vector', models.JSONField(default=dict)),
                ('pairwise_combinations', models.JSONField(default=dict)),
                ('KPIs_selected_names', models.TextField(default='[]')),
                ('selected_objectives', models.TextField(default='[]')),
                ('objectives_scores', models.JSONField(default=dict)),
                ('objectives_inconcistency', models.TextField(default='[]')),
                ('objectives_vector', models.JSONField(default=dict)),
                ('pairwise_combinations_objectives', models.JSONField(default=dict)),
                ('BSC_Weights', models.TextField(default='[]')),
                ('selected_criteria', models.TextField(default='[]')),
                ('criteria_scores', models.JSONField(default=dict)),
                ('criteria_inconcistency', models.TextField(default='[]')),
                ('criteria_vector', models.JSONField(default=dict)),
                ('pairwise_combinations_criteria', models.JSONField(default=dict)),
                ('criteria_selected_names', models.TextField(default='[]')),
                ('shapes', models.TextField(default='[]')),
                ('matrix_data', models.JSONField(default=dict)),
                ('matrix_data_pre', models.TextField(default='[]')),
                ('results', models.TextField(default='[]')),
                ('hierarcy', models.TextField(default='[]')),
                ('supermatrix', models.TextField(default='[]')),
                ('rows', models.TextField(default='[]')),
                ('comments', models.TextField(default='')),
                ('message', models.TextField(default='')),
                ('user_domain', models.CharField(choices=[('MANUFACTURING', 'Manufacturing'), ('AEROSPACE', 'Aerospace'), ('COMMUNICATIONS', 'Communications'), ('CHEMICAL_AND_PHARMACEUTICAL', 'Chemical and Pharmaceutical'), ('CONSUMER_GOODS_AND_RETAIL', 'Consumer, Goods, and Retail'), ('ENERGY_AND_UTILITIES', 'Energy and Utilities'), ('FINANCIAL_SERVICES', 'Financial Services'), ('FREIGHT_LOGISTICS_AND_TRANSPORTATION', 'Freight, Logistics, and Transportations'), ('HEALTH_AND_LIFE_SCIENCES', 'Health and Life Sciences'), ('HOSPITALITY_AND_TRAVEL', 'Hospitality and Travel'), ('MEDIA_ENTERTAINMENT_AND_PUBLISHING', 'Media, Entertainment, and Publishing'), ('RD_AND_EDUCATION', 'R&D and Education')], max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('criteria', models.ManyToManyField(to='ANPAHP.criterion')),
                ('KPIs', models.ManyToManyField(to='ANPAHP.kpi')),
                ('objectives', models.ManyToManyField(to='ANPAHP.objective')),
            ],
        ),
    ]
