# Generated by Django 5.1.7 on 2025-04-04 09:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANPAHP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.TextField(unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='option',
            field=models.CharField(blank=True, choices=[('COST_AND_COST_REDUCTION', 'Cost and Cost Reduction'), ('PRODUCTIVITY_INCREASE', 'Productivity Increase'), ('QUALITY_AND_DATA_INCREASE', 'Quality and Data Increase'), ('SAFETY_INCREASE', 'Safety Increase'), ('LEARNING_AND_GROWTH_INCREASE', 'Learning and Growth Increase'), ('USER_SATISFACTION', 'User Satisfaction')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='objective',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
