# Generated by Django 5.1.7 on 2025-05-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ANPAHP', '0006_evaluation_interfamily_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='alternative_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
